/** Declaration file generated by dts-gen */
interface Cordova {
    openwith: typeof openwith
}

declare namespace openwith {
    const DEBUG: number;

    const ERROR: number;

    const INFO: number;

    const SEND: string;

    const VIEW: string;

    const WARN: number;

    function about(): any;

    function addHandler(callback: any): void;

    function exit(): void;

    function getVerbosity(): any;

    function init(successCallback: any, errorCallback: any): void;

    function load(dataDescriptor: any, successCallback: any, errorCallback: any): void;

    function numHandlers(): any;

    function reset(): void;

    function setCordova(value: any): void;

    function setLogger(value: any): void;

    function setVerbosity(value: any): void;

}

