* [2018-6-23 Sat] Change the ~poster~ of ~video~ tag
Originally, I tried to change the ~poster~ to be an image; however, setting ~height: 100%;~ is useless.
Finally, I tried the method described in [[https://stackoverflow.com/questions/10826784/make-html5-video-poster-be-same-size-as-video-itself/][this StackOverflow's Q&A]] to solve this problem.
1. Set the ~video~ element's ~poster~ attribute as ~data:image/gif,AAAA~ which is a DataURI of an unloadable image to clean up the poster.
2. Set the size of ~video~ by
#+begin_src css
video{
    height: 100%;
    width: auto;
    max-width: 100%;
    background: transparent no-repeat url('/assets/i18n.svg');
    background-size: contain;
    background-position: center;
}
#+end_src
so that it can be fit into the grid correctly.

* [2018-6-22 Fri] Let it can run on Android and on older version.
In order to run in on Android platform, I need to
1. Install the Visual Studio hyper-V android emulator.
    a. Find the emulator. You can find it by searching ~Visual Studio Hyper-V Android Emulator~.
    b. If you have installed ~Android Studio~, the ~adb~ might be at ~\~/AppData/Local/Android/Sdk/platform-tools/~.
    c. Follow the instruction shown in [[https://stackoverflow.com/questions/32088648/visual-studio-emulator-for-android-devices-are-not-listed-in-the-android-devic][in this StackOverflow's Q&A]], you can let adb can find your running emulator.
    d. Another important thing is about how to debug your ~js~ code. The answer is shown in [[https://stackoverflow.com/questions/21332853/is-there-a-real-solution-to-debug-cordova-apps][this StackOverflow's Q&A]].
       You just need to run ~chrome://inspect~ in Chrome and it will show your devices with running Apps. You can debug it as a web site.
       For iOS, you can use safari to do this job. (iOS)Safari, Web inspector on ==> (iMac) Safari, Develop, your device.
2. Run ~ng~ with ~--base-href ./~ or ~--base-href /android_asset/www/~ for android platform.
   Hm... at this moment I set ~--base-href ./~ for all platforms.
3. The OS of android emulators are too old, I need to do some extra works.
    a. As [[https://stackoverflow.com/questions/45300670/uncaught-typeerror-usevalue-usefactory-data-is-not-iterable-angular-4-cli-proj][this StackOverflow's Q&A]] mentioned, I need to modify ~polyfills.ts~ as it said. However, I'll encounter a problem in which it said that ~__zone_symbol__then~ is not a function. [[https://github.com/angular/zone.js/issues/1078][Soultion?]], no use.
    Then I need to declare ~es6_shim~ in ~index.html~.
    b. Although it can work, the ~back~ key's function is wrong, and if you want to play the Youtube video, it will collapse the whole App on the emulator (can work on my device). 

* [2018-6-21 Thu] Now it can play Youtube on Angular and Windows App
1. In ~tsconfig.app.json~, I added ~youtube~ into the list of ~types~.
2. Generate a Service ~youtubeService~ to serve the job with Youtube and embedded youtube Api in ~ngOnInit~.
3. In [[https://stackoverflow.com/questions/38008334/angular-rxjs-when-should-i-unsubscribe-from-subscription][this StackOverflow's Q&A]] you can see how to unsubscribe the subscriptions from ~subject~s by one ~Subject~ that me named it ~unsubscribed~.
In that answer, you can find that he use ~takeUntil~ to unsubscribe all the subscriptions which call this function.
How to enlive this ~takeUntil~? Use ~unsubscribed.next(); unsubscribed.complete();~ to trigger it.
So I put this code in ~ngOnDestory~ so that it will unsubscribe all subscriptions when you want to leave that ~component~.


* [2018-6-19 Tue] Try to embed Youtube into this App.
Follow the tutorial from [[https://stackoverflow.com/questions/36467532/][this stackOverflow's Q&A]], I want to make it work in this App.


* [2018-6-18 Mon] MediaEditService as the data center for all elements of MediaEditComponent
I put all ~subject~s (the event emitter & listener) and datas into ~MediaEditService~ so that all the members of ~MediaEditComponent~ will use ~MediaEditService~ as the data center.
It works.

* [2018-6-12 Tue] Fail to run this App in Android device and emulator
Once I set the ~Debug mode = true~ on my Android Laptop, I can run this App on that device; however, nothing is shown up.
Besides, I cannot find ~adb~ in ~Android SDK~'s folder. Because of that, I cannot choose the one provided by Visual Studio which is running under Hyper-V whose performance is quite nice.

* [2018-6-11 Mon] Let angular can compile the stuffs for Windows
1. ~npm install --save-dev @types/winrt~ to let Angular can recognize ~Windows.Storage~ namespace.
2. Since ~documentsLibrary~ cannot be declared in ~appxmanifest~ file, I changed to use ~videosLibrary~ and it works.
3. Three roles: a.~video Element~, b.~File(Blob)~ and c.~StorageFile(Windows)~.
    b,c -> a: ~url=window.URL.createObjectURL(b)~. However, this method is not suitable for the ~File(plugin)~, it should be gotten from ~fileEntry.toURL()~.
    a -> b,c: ??? Fortunately, I don't need it at this moment.
    b -> c:   ~input=b.msDetachStrem();~, ~output= await c.openAsync();~ and copy ~b~ to ~c~ by ~Windows.Storage.RandomAccessStream.copyAndCloseAsync(input,output)~.
    c -> b:   ??? Hm. I still don't need it.

* [2018-6-8 Fri] Using cordova and its file plugin in Angular 6.
1. In ~tsconfig.json~ file, I added in ~"cordova-test/plugins"~ in its ~"typeRoots"~ so that angular can use the typescript's declarations inside.
2. In ~/src/tsconfig.app.json~ file, I added in
#+begin_src json
    "types": [
      "cordova",
      "cordova-plugin-file/types"
    ]
#+end_src
in its property ~compilerOptions~ so that I can use "cordova" and "cordova.file" in this code.
3. Oh, remember that, you need to run
#+begin_src sh
npm i --save-dev @types/cordova
#+end_src
to let angular can recognize the object ~cordova~.
However, if you want to check whether it is supported,
~!!cordova~ will throw an error. You'd better to use ~!!window.cordova~ to check whether it is supported.

By the way, because ~ng build~ will remove the target folder at first, it will cause ~cordova~ think that it is not a cordova project if the building is fail.
How to solve this problem?

WELL, ADD AN EMPTY ~www~ FOLDER INSIDE CAN MAKE IT WORK.

* [2018-6-7 Thu] Load local file and play it by File API.
At this moment, I still not use cordova's plugin. I still use ~File API~ to achieve my goal.
1. I can get ~FileList~ from ~input~ with type of ~file~.
2. Then I use ~window.URL.createObjectURL(file)~ to get a temporary URL.
3. If I feed it directly to ~[src]~ of the UIElement audio, it will say that it is unsafe; therefore, I create a new pipe to tell Angular 6 to accept this URL as mentioned in [[https://stackoverflow.com/questions/41319324/angular-2-http-request-audio-src-not-play][this stackOverflow's Q&A]].
4. Even I take out the ~type~ of the ~HtmlMediaElement~, it still can work. However, it cannot play the ~WMV~ movie.
    But, the ~WMV~ can be played in Windows UWP!!! Great! That's enough.

* [2018-6-6 Wed] Try to disable the zoom in/out behavior in windows UWP
Once I added in 
#+begin_src css
body{
    margin: 0;
    -ms-content-zooming: none;
}
#+end_src
the zooming behavior is disabled in Windows UWP.

* [2018-6-4 Mon] Try to use display:grid in css file.
Well, ~route-outlet~ itself is an empty one. If you want to control its size by grid, you need to contain it into a ~div~ and set the grid control on that container ~div~.

* [2018-6-4 Mon] A navbar has been added.
I'm reading [[https://css-tricks.com/snippets/css/a-guide-to-flexbox/][this article about flex]] to know how to settle a better layout.
I'll apply it in next commit with the route.

* [2018-6-2 Sat] How to use mat-icon?
Well, as mentioned in [[https://material.angular.io/guide/getting-started][this article]], I need to add 
#+begin_src html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
#+end_src
into ~index.html~ file.
This way is still work in Windows APP.

* [2018-6-1 Fri] Now, how to debug this code?
1. ~ng serve~ + ~DEBUG: Launch Chrome~ in VS Code.
    - By this way, you can set break point in VS Code and to see what's happened in this code.
    - The web page will be renewed once you save the file.
2. ~cd cordova-test && cordova build windows~ and then run it in VS2017.
    - Once I need to check how does it work and debug it in a windows App, I need to do so.

* [2018-5-31 Thu] Make it can be debugged in Visual Studio 2017
1. Add in ~<script src="cordova.js"></script>~ into ~index.html~ by the command shown below and you need to add an anchor in ~index.js~ as ~<!-- EntryOfCordovaJS -->~; otherwise, it still can work in VS2017 out of cordova's functions.

2. Use 
#+begin_src sh
ng build --output-path cordova/www/ --base-href /www/ && sed -i "s/.*EntryOfCordovaJS.*/  <script src='cordova.js'><\/script>" cordova-test/www/index.html
#+end_src
so that its output js files will be with their sourcemaps, which means that it can be debugged in VS 2017.
However, for ~prepareAngular6App.js~, I need to write it as
#+begin_src sh
"ng build --output-path cordova-test/www/ --base-href /www/   && sed -i \"s/.*EntryOfCordovaJS.*/  <script src='cordova.js'><\\/script> /\" cordova-test/www/index.html"
#+end_src
Note that, the ~"~ after ~sed~ cannot be ~'~; otherwise, it'll not work.

3. Use
#+begin_src 
    mklink /j cordova-test[2018-6-1 Fri]\platforms\windows\src src
#+end_src
to make a junction (just as soft link) to src so that it can be debugged in VS2017.

4. To avoid to do unnecessary Typescript compilation, you can add 
#+begin_src xml
    <PropertyGroup>
        <TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
    </PropertyGroup>
#+end_src
into your ~CordovaApp.Windows10.jsproj~ file to turn the compilation from VS2017 off since I'll compile it through angular 6.
* [2018-5-25 Fri] Yes, it can work for Windows 10 & Browser
The command for angular build should be
#+begin_src sh
ng build --prod --output-path cordova/www/ --base-href /www/
#+end_src
Now, I'm facing two problems.
1. how to debug it since it has been uglify?
2. how to use ~app~ which is ~WinJS.Application~ as the role of the class of ~App.xaml.cs~?

* [2018-5-23 Wed] ng is created with cordova
Following [[https://www.becompany.ch/en/blog/2016/10/19/creating-apache-cordova-app-with-angular2][this article]], we can make an angular with cordova.
#+begin_src sh
ng new cordova-ng-test
cd cordova-ng-test
cordova create cordova
#+end_src
