* [2018-9-17 Mon] Ok. Make a Youtube video to introduce this App.

* [2018-9-16 Sun] Oh. I can see the Ad. from AdMob on Android platform.
In this commit, I have shown an alert to let the user know that they will see an Ad. before they switch to another story. 

* [2018-9-16 Sun] .gitignore just can ignore the untracked files
If you do really want to ignore some tracked files or folders, you need to run 
#+begin_src sh
git rm -r --cached <folderName>
git add .
#+end_src
well, then they'll be ignored.

* [2018-9-14 Fri] I have applied a new AdMob account and now I need to think about how to keep these Id privately.
1. I got an id for android system for AdMob; however, it shows nothing. I am not sure whether it works.
2. I want to keep my Id privately, but how? Thinking.

* [2018-9-14 Fri] Now I can create a android bundle.
1. You need to download Android studio >3.2 version so that it can create a bundle one.
2. Once you finished the extraction of the Android Studio's zip file, run ~bin/studio64.exe~
3. It will update gradle to version 4.6 and of course you'll face the error again.
4. Change 4.4 to 4.6 as mentioned previously, *restart the computer* because some folders are locked and ~cordova build android~ again.
5. Get into AS3.2 again and this time it might show other errors such as you declared ~minSdkversion~ at wrong position and they can be fixed easily by clicking its autofix.
6. Finally, I can create a signed bundle. Interestingly, I still need to create a keystore with key... Hm. this key should be for public key.

* [2018-9-13 Thu] Update the gradle from 4.1 to 4.4
Modify the value in ~gradle-wrapper.properties~, ~app/build.gradle~, 
~GradleBuilder.js~, ~StudioBuilder.js~
That's all. Commit again.

* [2018-9-13 Thu] I want to build it as a bundle, but how?

* [2018-9-13 Thu] If you want to set ~android-minSdkVersion~ in ~config.xml~, don't set it too high.
Because I set it too high, I cannot install it on my Laptop since its SDK version is 24 and this one cannot be changed by hand.

* [2018-9-12 Wed] I have given it a version and it does really change the version shown in windows uwp.
Windows uwp can generate all icons automatically; however, some of them are too small.
Owing to the benefit of git, I can change some of them back to its original one.

By the way, I also try to let Youtube to change the name just when the video is just initialized from url string not from other types.

* [2018-9-12 Wed] After installing cordova-icon and cordova-splash, I can generate the icons automatically.
Remember that, I change the widget id of cordova so I need to remove ~ios~ and ~osx~ at first and then add them in again.

* [2018-9-11 Tue] Using ~document.activeElement~ to check whether the textarea is focused.
1. Remember that, it takes time to get focus, so I use an ~await~ about 100ms before checking it.
    Not so beautiful solution. If I can get its event will be better.
    a. Remember that, once you ~cordova platform add android~, copy the file ~gradle.properties~ to ~./platforms/android~.

2. Now I want to generate icons automatically.

* [2018-9-10 Mon] Now I'm stuck in building for Android.
1. As [[https://stackoverflow.com/questions/49208772/error-resource-androidattr-fontvariationsettings-not-found][this StackOverflow's Q&A]] mentioned, I need to install the plugin ~cordova-android-support-gradle-release~ so that I can pass the problem coming from gradle.
However, I have no luck. Maybe my version of Android SDK is too old and I need to update it?
I'm not sure.

2. I cannot successfully remove the plugin ~cordova-android-support-gradle-release~, let me commit it at first and then test for it.

3. Now I'm installing the update of Android SDK 28, I'm not sure whether it can work.

4. Finally, I did not install that plugin and just add a new file ~gradle.properties~ to set ~cdvCompileSdkVersion=android-28~ as describe in [[https://cordova.apache.org/docs/en/latest/guide/platforms/android/][Cordova's Guide]] and some other discussions and it works!

* [2018-9-10 Mon] Change to use file-opener2 for ios 
1. Since that, I removed cordova-plugin-x-socialsharing since ~file-opener2~ will do similar job.

2. By the way, using ~cordova prepare osx~ and then compiling it in XCode can load all plugins correctly in OSX.

3. Because the filePath will be encoded before sending to ~file-opener2~, I need to ~decodeURIComponent(filePaht)~ before sending to it. After this modification, it works fine in iOS now.

* [2018-9-7 Fri] About transition -> animate, the delay part will affect the previous one.
Because when the user touch the screen, it will trigger the state 'show' first and change to 'hide' immediately.
Well, you'll see that it shows up in a very low pace as the time period of delay of state 'hide'.
So, I use ~await of(true).pipe(delay(300)).toPromise()~ for changing to state 'hide' so that the whole process of the state 'show' can be finished.
By the way, I have applied a web URL as ~yescirculation.at.tw~ and apply an id from google play.

* [2018-9-6 Thu] Testing socialsharing in windows and android. Looks like that it can coexist with my code.

* [2018-9-5 Wed] For ios, ~cordova-plugin-x-socialsharing~ does not work correctly.
Because the user cannot get the file directly from the folder in ios, I decided to use the plugin ~socialsharing~.
However, it will crash at the first time loading and sharing file in my App will crash.
Well, finally, I decided to share its texts. I don't like it.

* [2018-9-5 Wed] For osx, we can use cordova.file.documentsDirectory directly without any permission
So, in this commission I just modify one file ~fs.service.ts~ to use the ~Documents~ folder as the folder for sharing files with others.

* [2018-9-5 Wed] At this moment, both windows and android can save files now.
1. For windows uwp, I chose to use FileSavePicker to deal with this saving file's problem.
2. For android, I chose to use the plugin ~cordova-plugin-android-permissions~ to deal with this problem.
    By the way, remember to add in two preferences about ~file~ into your ~config.xml~ file.
3. Sigh, ~alert~ also cannot be used in cordova; therefore, I create one for myself.

Now, I need to switch back to Mac to test it in ~ios~ and ~osx~.

* [2018-9-3 Mon] Oh. Bad news, <a download ...> does not work for ios and osx
1. Even after I add
#+begin_src xml
    <allow-navigation href="blob:*" />
    <allow-intent href="blob:*" />
#+end_src
into config.xml file.
I just can see them, but I cannot get them....
I need to find a new way to save them.

2. By the way, when you run ~cordova plugin add PLUGIN~, don't forget to add ~--save~.
    If not, the plugin may not be added into your platform.

3. Some error might be caused by the off of ~Capabilities -> App Sandbox -> Network: Outgoing Connections (Client)~, I'm not sure.
* [2018-9-2 Sun] Some problems happened in osx
1. Plugins Admob & Clipboard do not support osx, so I need to control this problems in my ~services~.
2. The structure of plugin Clipboard is not too hard, maybe someday I can try to write one for osx.
3. I need to run ~cordova platform remove osx; cordova platform add osx~ to force it to include the information of plugins into ~config.xml~ file in ~osx/HelloCordova~. Otherwise, if you build it from cli again will lose these information and you can see the error of missing plugins from XCode.
4. In ~me-mani-dashboard.component~, the ~<div>~ always on the top of ~<textarea>~ so that I use ~[style.display]~ to hide it forcely.
5. Well, finally, I got an error: ( sendMessageWithDictionary: Failed to get remote object proxy: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.rtcreportingd" ).
   I tried to find a solution since it will affect how I get the ~innerText~ of ~<div>~.
6. By the way, I still don't know how to debug the javascript part of my APP in osx system.

* [2018-9-1 Sat] Modify the original cordova-plugin-tts to output voice.name & set its pitch
1. If you want to change an exist cordova plugin, the better way is to clone it outside your cordova App's folder.
   Once you modify it, run ~cordova plugin remove PLUGIN~ and then ~codova plugin add LOCAL_PLUGIN_FOLDER~ to renew it so that your modified plugin will be compiled correctly.
2. Because the name of android's voice is not user friendly, I need to use a function to transform that name instead of get the name directly.
   By the way, I use ~i18n-page-texts~ to handle the names for the user. Well, it takes a lot of time and crashed at ~indonesian~.
3. I try to renew the whole ~voices~ to notice Angular that it should be dealt as a new one so that it will try to recall the function after I change page texts.

* [2018-8-29 Wed] Oh, SpeechSynthesis does not work in Android's webview. I need to do it through native code (plugin).
1. ~min-height: 0~ is necessary for an item of ~grid~ when the height of that item is larger than that sub-grid's height.
2. I need to scroll, so I put the one I want to scroll into ~cross-comp.service~ and then I set its ~scrollTop~ to scroll it.
   Remember that, ~scroll(...)~ does not work in windows uwp.
3. ~mat-list~ cannot get its nativeElement.
4. As [[https://stackoverflow.com/questions/22143837/speechsynthesisutterance-not-working-in-an-html5-app-built-for-android][this StackOverflow's Q&A]], speechsynthesis does not exist in Android's webview. I need to install the plugin to call it natively.

* [2018-8-28 Tue] Multilingual
1. In ~story.component~, once I change language, the ~mat-select~ may throw an ~ExpressionChangedAfterItHasBeenCheckedError~ error sometimes. The good news is that it can be solved by ~ChangeDetectorRef~ as mentioned in [[https://stackoverflow.com/questions/47425569/angular-2-material-mat-chip-change-selected][this StackOverflow's Q&A]].
2. Oh, I need to remove the ~outDefaultFile~ and rename the ~outInterfaceFile~ to be ~....d.ts~, a definition ts file; otherwise, angular will show error messages of ~ts2304~ and ~ts2339~.
3. I add a property ~isShown~ in ~message.service~ to control whether to show messages.
   At this moment, I turned it off.
   One day, I want to toggle it in a global setting page.

* [2018-8-27 Mon] Blinking selected icon button.
Hm... ~color~, ~background-color~ and ~transform~ does not work for it, I used ~opacity~ finally.

* [2018-8-27 Mon] SpeechSynthesis II/II
1. Now it can utter each segment's subtitle when the global play reaches that segment.
   The ~media-edit.component~ handles it because maybe I need to show each subtitles.
2. It also can output the Youtube .sbv file now.

* [2018-8-26 Sun] SpeechSynthesis I/II 
1. Using a ~Subject~ to notice ~me-mani-plate.component~ that it will replay the section again.
2. Using ~flex-wrap: wrap~ to wrap the sliders in ~set-speech-synthesis.component~ automatically.
3. Remember that, ~Object.assign(target,source)~ will modify the ~target~. So, input ~{}~ as the target to copy an object.
4. Using a ~Subject~ ~setiFrame$~ in ~media-edit.service~ to give a notice about the ~iFrame~ is setted.
5. Before utter a sentence, it's better to ~pause~ -> ~cancel~ -> ~speak~ -> ~resume~; otherwise, it might not speak occationally.

Next, I want to let the user can use SpeechSynthesis in the whole story.

* [2018-8-21 Tue] Now, once I consider ~sanitizer.bypassSecurityTrustHtml~, I can input subtitles with custom styles.
By the way, I need to provide a min-height for the textarea so that the pointerleave event will not be triggered when my finger leaves the textarea.

* [2018-8-21 Tue] ~i18n-page-texts~ is updated and the user can export and import ~story~ now
1. when generating a story, its ~modifyTime=0~ so that I can use this value to make sure whether it is a new one.
2. when youtube is ~onReady~, getting its title and set it as the name of that ~story~.
3. let ~media-edit.service~ to handle the methods ~onSaveStory~ and ~onUpdateStory~.
4. let those ~.json~ files for stories can be loaded in through ~File~ button.
5. oh, an important thing need to be mentioned. Microsoft's browser doesn't allow ~dataURL~, so, I changed to use ~Blob~ and it works fine.
6. remember that ~!!cordova~ might throw an error, you need to use ~!!window.cordova~.

* [2018-8-18 Sat] AdMob has been installed.
1. I have installed ~cordova-plugin-admobpro~ and created a service ~ad.service~ to handle Windows Ad & Android and iOS Ads.

2. The folder named as isoCode such as ~en~ or ~zh-tw~ will cause a problem in windows system. I need to rename them to be such as ~iso_zh=tw~. It means that I need to modify my ~i18n-page-texts~ node package.

* [2018-8-15 Wed] I have tested ~i18n-page-texts~ and it works fine in ~home.component~ on both windows and Android.
Once the effort for ~page-texts.service~ is done, I can easily use it in my code.
At this moment, I have tested it on ~home.component~ in Windows & Android system.

* [2018-8-11 Sat] Using Cordova-Clipboard to handle clipboard.
It works for Android and Windows UWP.
But the method ~paste~ of ~ClipboardProxy.js~ of [[https://github.com/ihadeed/cordova-clipboard][this plugin]] has a problem.
They forget to handle the case of nothing inside the clipboard.
This part you need to modify this code in ~platform-www~.

Besides, I learned an important concept about ~Promise~.
Remember that, the ~Promise~ will store its ~resolve~'s result and it will use the previous value instead of running the script again.

Therefore, for this clipboard, I need to create a new ~Promise~ for each call; otherwise, it will behave strangely.

You can test it by 
#+begin_src javascript
var i = 0;
var promise1 = new Promise(function(resolve, reject) {
  setTimeout(resolve, 100, 'foo'+(i++));
});

promise1.then(console.log);
promise1.then(console.log);
#+end_src
and you'll get ~foo0  foo0~ instead of ~foo0 foo1~.

* [2018-8-9 Thu] Load material icons offline
As mentioned in [[https://github.com/angular/angular-cli/issues/2662][this angular's Q&A]], once ~@import "~material-design-icons/iconfont/material-icons.css";~ is declared in ~styles.css~, the icons can be loaded offline.
Oh, don't forget to install ~material-design-icons~ at first.

* [2018-8-9 Thu] Testing on oPPo
Hm... Input numbers form keyboard is not a good idea on a mobile, I add in two ~observable~ to handle the pointer events to increase or decrease start and end times.

By the way, don't import ~pepjs~ for android and windows system might be a good idea since sometimes it makes the pointer control a little wierd. 

Oh, one more thing. the ~accept="video/*,audio/*"~ does not work for a ~file input~. People said that I had better to use two buttons for them.
However, for windows App, ~accept~ does not work. So, I need to find a better way.

* [2018-8-8 Wed] It can work on iOS and macOS now
To let it can run on iOS and macOS, you need to do something
1. you need to install pepjs and declare it in ~polyfills.ts~ file so that it will be loaded just like declaring ~<script src=....>~ in index.html. The better thing is that it will be compiled into your code instead of calling that js file from network.
2. you need to declare ~touch-action="none"~ as an attribute instead of just a CSS style for iOS system. Please read this [[https://github.com/jquery/PEP/issues/211][Q&A of PEP]].
3. to avoid showing videos in Full screen, you need to 
    a. declare ~<preference name="AllowInlineMediaPlayback" value="true" />~ in config.xml file.
    b. add attribute ~playsinline~ for a ~<video>~ element.
    c. add ~playsinline=1~ into youtube's query string.
4. to let iOS can call ~https://www.youtube.com~, I need to add
#+begin_src xml
    <allow-navigation href="http://*/*" />
    <allow-navigation href="https://*/*" />
#+end_src
    into config.xml file as described in [[https://cordova.apache.org/docs/en/latest/guide/appdev/whitelist/#ios-whitelisting][this Cordova's Doc]].
5. add ~<preference name="iosPersistentFileLocation" value="Library" />~ into config.xml for iOS; otherwise, it does not store data and quit the App directly.
6. Seeking time might be larger than the setted time in iOS system. So I need to check whether it is in starting in ~player.component.ts~; however, I don't think that I wrote it in a safty way. Let me think later. 
7. by the way, checking whether
#+begin_src xml
    <engine name="ios" spec="^4.5.5" />
    <engine name="osx" spec="^4.0.1" />
#+end_src
are adding into your config.xml file. If not, you will find that your macOS or iOS App will out of plugins.
i.e. no file and sqlite plugins.

By the way, nanoSQL has updated its code so that 'trie' can use again now.
* [2018-8-6 Mon] It can save a file to ~dataDirectory~ and play it.
However, for some files in android it cannot be stored into ~dataDirectory~. Size problem?

* [2018-8-5 Sun] Testing File plugin & nanoSQL on Windows & Android
1. Well, ~file plugin~ works fine in these two platforms; however, for a browser, it looks like that I need to query a suitable quota at first. Hm... Skip this one at this moment.
2. There's a problem for deleting a row from nanoSQL table for devices. If your query in your ~where~ statement is for ~id~ which is a pK, it will delete nothing. Hm... If you look into the code, the problem happens at ~cordova-nanoSQLite:sqlite-adapter:batchRead~ function.
Sigh, how to debug it? It means that I need to understand how to use ~SQLite plugin~ before solving this problem.

* [2018-8-3 Fri] That's a promise racing, setting ~cache:false~ can avoid it.
1. Has written a possible solution for the author. Hoping that he can solve it.
    At this moment, I tried to compile it but has no luck. I cannot compile it successfully.

2. By the way, for ~cordova run browser~, setting ~mode:'PERM'~ to avoid using SQLite3 plugin of cordova and it works. ^_^

* [2018-8-2 Thu] Well, the problem is happened at ~storage.ts~ of ~nano-sql~.
The problem is that ~rebuildIndexes~ function itself in fact is an async and its ~FastAll~ promise does not work in right sequence since it is a real asynchronized function.
So, the ~_secondaryIndexUpdates[idxTable]~ will be cleaned by ~_flushIndexes()~ before using it.
Let me try to modify it.
Before that, let me commit this code at first.

By the way, if you want to exclude something in ~.gitignore~ as mentioned in [[https://stackoverflow.com/questions/5533050/gitignore-exclude-folder-but-include-specific-subfolder][this StackOverflow's Q&A]].
So, ~dir/~ and ~dir/*~ are not the same. 
The first one ignore ~dir/~ itself so that the exclusion under it won't work.
You need to use ~dir/*~ so that ~dir~ will be checked even if all its subfolder will be ignored.

* [2018-8-1 Wed] I don't know what's wrong when I compile this code in windows
When I call ~await nSQL(...).connect();~ will give me an error in windows system. I don't know what's wrong.

* [2018-7-31 Tue] Looks like the size of Element inside a Grid will be justified automatically so it is not suitable to set your Element's size.

* [2018-7-30 Mon] For dynamic css class, you can use ::ng-deep to rewrite its rule
As mentioned in [[https://stackoverflow.com/questions/44386840/angular-2-material-md-tab-size][this StackOverflow's Q&A]], I can use ~::ng-deep~ to achieve that dynamical class. You can read more details from [[https://angular.io/guide/component-styles][angular's Doc]].

* [2018-7-30 Mon] If you want to keep the mousedown event as the 1st emittion, you can do as follows
#+begin_src js
    this.resize$.pipe(
      map(ev => of(ev).pipe(
        concat(of(ev).pipe(
        map(_ => self.device.onPointermove$.pipe(
          takeUntil(self.device.onPointerup$),
          concat(of(null))
        )),
        concatAll()
      )))),
      concatAll()
    )
#+end_src

* [2018-7-29 Sun] Do something when I change the frame and deal with playbackRate and volume.
1. Write a method named ~setiFrame(i: number)~ instead of setting iFrame directly so that I can do something when I want to change frame.
2. Let ~me-mani-plate.component~ can set ~volume~, ~playbackRate~, etc.
    However, the more I write it, the more I feel that the ~player.component~ should be a server. If it is a client, I just can talk to it by ~Subject~ or ~event~ and cannot access its methods and properties directly.
3. By the way, the ~playbackRate~ of Youtube is limited, I need to get it every time I get a Youtube video.
    Hm... Let me think about making ~player.component~ a server seriously.

* [2018-7-27 Fri] Setting up basic animations for ~me-mani-plate.component~
In [[https://github.com/ableplayer/ableplayer]], it has the possibility to get the captions' information with timeline;
however, it is not a short program. I want to deal with it later.

* [2018-7-25 Wed] Use ~svg:rect~ to denote each frame (section)
1. If you want your ~svg~ to fit the size of a grid, you can declare a suitable ~viewBox~ as its original size and ~[attr.preserveAspectRatio]="'none'"~ because the default is that the ratio of width/height is fixed.
Well, reading [[https://stackoverflow.com/questions/19484707/how-can-i-make-an-svg-scale-with-its-parent-container][this StackOverflow's Q&A]] to get some ideas. 
Well, after that I don't need to worry about changing the size of svg's container.

For more information, you can google ~svg mdn~ or ~preserveAspectRatio mdn~, they have some useful documents.

2. The ~$event.target~ might not be the one call the event, it might be its child.

* [2018-7-23 Mon] It can set current time from main dashboard now.
Achieve this goal by ~seekTo~.

In [[https://angular.io/api/common]], you can find a useful pipe named ~DecimalPipe~.
Before you use it, you need to ~import~ ~CommonModule~ into your AppModule.

* [2018-7-22 Sun] Add swap-icons into me-section-dashboard
Now, the icons will get their color randomly.
By the way, I use observable ~interval~ to check the current time of player.

* [2018-7-20 Fri] Make the action of opening an existing story or creating a new story of ~HomeComponent~ work
Ok, now from ~HomeComponent~ to ~MediaEditComponent~ and ~NavbarComponent~ through setting ~MediaEditService~ is done.

It's time to set each section.

* [2018-7-18 Wed] About flex
As described in [[https://stackoverflow.com/questions/36182635/making-a-flex-item-float-right/36182782][the answeer of this StackOverflow]], setting ~margin-left: auto;~ will push the HtmlElement to the right if its parent's display is ~flex~.
By the way, changing its ~order~ can make it as a floating element, i.e. does not affect others' order.

* [2018-7-18 Wed] Handling Pointer events
1. Although ~pointer events~ are not supported by ~safari~, it might be solved by [[https://github.com/jquery/PEP][jQuery PEP]] or follow the solution shown in [[https://www.sitepoint.com/unifying-touch-and-mouse-with-pointer-events/][this page]]. Not yet test it.
2. Maybe ~hammer.js~ is another solution, it provides a lot of gesture events. Not yet read [[https://blog.angularindepth.com/gestures-in-an-angular-application-dde71804c0d0][this blog]].
3. IMPORTANT. As described in [[https://stackoverflow.com/questions/48124372/pointermove-event-not-working-with-touch-why-not][the Answer of this StackOverflow]], some of the ~pointer~'s actions might be canceled by ~browser~'s ~touch-action~ such as ~pointerup~ and ~pointermove~.
The solution is to set ~touch-action: none;~ to the style of the manipulated HtmlElement.

* [2018-7-16 Mon] Angular 6 cannot build in inline source map.
Hm... Setting in ~tsconfig.json~ cannot make it work.
Well, I try to install augury and see what I can do for the debugging of Angular 6 as described in [[https://coryrylan.com/blog/angular-debugging-tips-and-tricks][by this site]].

* [2018-7-15 Sun] Using mat-side-nave and find a problem about Youtube API
Hm... the ~onStateChange~ event of Youtube Player will not work after you run ~loadVideoById(...)~, a completed observable problem?
Well, someone suggests that it can be solved by ~setTimeInterval~ just like "123, wooden men" did.
However, I don't like this way. I do not solve this problem at this moment.

* [2018-7-14 Sat] Some problems about nSQL
1. Always provide ~where~ condition for query ~delete~. 
    It is serious for windows platform. If out of ~where~, it will clear the whole table instead of just rows and windows system will prevent your query for ~upsert~ and it demands that you need to provide a primary key even it will be automatically generated.
2. Always just ~connect~ nSQL once, because each extra ~connect~s will create a new database and the query for ~upsert~ will apply on that new database as updating the deleted rows.
    By the way, the action of ~disconnect()~ is useless.
3. Anyway, now it works fine on browser, windows and android.

* [2018-7-13 Fri] Select, Upsert and Delete are embedded in DbService.
However, once I modify the model, it will create a new database.
Therefore, oneday if I want to update the ~model~, I need to delcare both the old one and new one to switch them.
I still don't wanna coding this part.

* [2018-7-11 Wed] Try to use the sticky-observable to dealing with the initialzing of nanoSQL and try to correct the bug about the state of Youtube.
1. The original ~cordova.require('cordova/channel').onDeviceReady~ does not have some methods such as ~pipe~ so I use a new observable to subscribe it and send ~observer.complete()~ when the deviceReady event is triggered. 
Then, I can use ~await ....toPromise();~ to await it and don't need to unsubscribe it.

2. Well, I enclosed the subscription of Youtube's ~onStateChanged~ observable and it seems works fine.
Originally, I might need to click twice to make the action of ~play~ and ~pause~ work.

* [2018-7-9 Mon] Dealing with ~sticky-observable~
Well, I tried to handle its ~TeardownLogic~ so that the subscribers can be unsubscribed from its ~_subject~.
Besides, I also try to let all observers subscribe ~self._subject~ instead of ~sticky-observable~ itself,
i.e. you need to store the 1st observer for this subscription.

Then, the question is that how to trigger the original subscription function?
Well, I can get the ~observer~ of ~self._subject~ through ~self.subscribe(self._subject)~ and run ~return fn(observer);~ so that the function of subscription will work on this ~self._subject~ so that it can alert all its subscribers.

* [2018-7-9 Mon] I tried to use nanoSQL and it works.
For installing nanoSQL, I need to install following packages at first.
1. I need to ~npm i nano-sql~ in this angular project.
2. I need to ~cordova plugin add cordova-plugin-nano-sqlite~ in folder ~cordova-test~.
3. Generate a class ~sticky-observable~ for some events like ~deviceReady~.
4. Using ~db.service~ to handle ~nSQL~'s job because I'm not sure whether it will be changed in the future.

For intellisense, I need to ~exclude: ['cordova','cordova-test']~ in ~tsconfig.json~.

* [2018-7-4 Wed] I created a dialog component and a story service. Next, I need to know how to use indexedDB.
I have learned:
1. Using ~FILEINPUT.click()~ to trigger the click event of a file input named ~#FILEINPUT~.

* [2018-6-27 Wed] Testing on windows, Android device and emulators
It works fine in ~ng serve~, ~Windows 10 App~, ~Asus P027~; however, the YouTube part will crash and the result of ~grid~ is wierd in ~Win10 Android Emulators~.

* [2018-6-27 Wed] Dealing with grid and some other problems
1. As [[https://stackoverflow.com/questions/43311943/prevent-content-from-expanding-grid-items][this StackOverflow's Answer]] said, I can disable the automation of ~min-width~ and ~min-height~ by decalring ~overflow: none;~.
By this way, the height of the grid's content never exceed the desired height.

2. Since I trigger ~onStateChanged~ when the user want to set the value of ~state~, I want its type is ~Observable<MEState>~ instead of ~Subject<MEState>~ when the caller want to use it. Well, I can use 
#+begin_src javascript
_onStateChanged: Subject<MEState>; // Just for subscribe, if you want to trigger it, set ~self.state~.
  public get onStateChanged(): Observable<MEState> {
    return this._onStateChanged;
  }
#+end_src
to achieve this goal.

3. Now I use ~pageType~ with ~[style.display]=...~ to toggle the display of pages instead of using ~router~.


* [2018-6-25 Mon] I want to get data from ~share~ of other applications.
[[https://stackoverflow.com/questions/16908224/share-something-to-a-phonegap-app][this StackOverflow's Q&A]] provide some ideas that I can try later.

* [2018-6-24 Sun] Cross platform's problem
The problem of ~base~.
1. For ~ng serve~: its base is /
2. For ~windows~, its base is ~/www/~
3. For ~android~, its base is ~/android_asset/www/~

that why I use ~<base href='./'>~ in ~index.html~ file. 
By the way, it may not be a good idea to use ~route~ since it will work wierd in Android system.

In html file, you can use related path; however, you must use absolute path in css.
So I use ~[style.CSS]~ in html file to solve this problem.

* [2018-6-23 Sat] Change the ~poster~ of ~video~ tag
Originally, I tried to change the ~poster~ to be an image; however, setting ~height: 100%;~ is useless.
Finally, I tried the method described in [[https://stackoverflow.com/questions/10826784/make-html5-video-poster-be-same-size-as-video-itself/][this StackOverflow's Q&A]] to solve this problem.
1. Set the ~video~ element's ~poster~ attribute as ~data:image/gif,AAAA~ which is a DataURI of an unloadable image to clean up the poster.
2. Set the size of ~video~ by
#+begin_src css
video{
    height: 100%;
    width: auto;
    max-width: 100%;
    background: transparent no-repeat url('/assets/i18n.svg');
    background-size: contain;
    background-position: center;
}
#+end_src
so that it can be fit into the grid correctly.

* [2018-6-22 Fri] Let it can run on Android and on older version.
In order to run in on Android platform, I need to
1. Install the Visual Studio hyper-V android emulator.
    a. Find the emulator. You can find it by searching ~Visual Studio Hyper-V Android Emulator~.
    b. If you have installed ~Android Studio~, the ~adb~ might be at ~\~/AppData/Local/Android/Sdk/platform-tools/~.
    c. Follow the instruction shown in [[https://stackoverflow.com/questions/32088648/visual-studio-emulator-for-android-devices-are-not-listed-in-the-android-devic][in this StackOverflow's Q&A]], you can let adb can find your running emulator.
    d. Another important thing is about how to debug your ~js~ code. The answer is shown in [[https://stackoverflow.com/questions/21332853/is-there-a-real-solution-to-debug-cordova-apps][this StackOverflow's Q&A]].
       You just need to run ~chrome://inspect~ in Chrome and it will show your devices with running Apps. You can debug it as a web site.
       For iOS, you can use safari to do this job. (iOS)Safari, Web inspector on ==> (iMac) Safari, Develop, your device.
2. Run ~ng~ with ~--base-href ./~ or ~--base-href /android_asset/www/~ for android platform.
   Hm... at this moment I set ~--base-href ./~ for all platforms.
3. The OS of android emulators are too old, I need to do some extra works.
    a. As [[https://stackoverflow.com/questions/45300670/uncaught-typeerror-usevalue-usefactory-data-is-not-iterable-angular-4-cli-proj][this StackOverflow's Q&A]] mentioned, I need to modify ~polyfills.ts~ as it said. However, I'll encounter a problem in which it said that ~__zone_symbol__then~ is not a function. [[https://github.com/angular/zone.js/issues/1078][Soultion?]], no use.
    Then I need to declare ~es6_shim~ in ~index.html~.
    b. Although it can work, the ~back~ key's function is wrong, and if you want to play the Youtube video, it will collapse the whole App on the emulator (can work on my device). 

* [2018-6-21 Thu] Now it can play Youtube on Angular and Windows App
1. In ~tsconfig.app.json~, I added ~youtube~ into the list of ~types~.
2. Generate a Service ~youtubeService~ to serve the job with Youtube and embedded youtube Api in ~ngOnInit~.
3. In [[https://stackoverflow.com/questions/38008334/angular-rxjs-when-should-i-unsubscribe-from-subscription][this StackOverflow's Q&A]] you can see how to unsubscribe the subscriptions from ~subject~s by one ~Subject~ that me named it ~unsubscribed~.
In that answer, you can find that he use ~takeUntil~ to unsubscribe all the subscriptions which call this function.
How to enlive this ~takeUntil~? Use ~unsubscribed.next(); unsubscribed.complete();~ to trigger it.
So I put this code in ~ngOnDestory~ so that it will unsubscribe all subscriptions when you want to leave that ~component~.


* [2018-6-19 Tue] Try to embed Youtube into this App.
Follow the tutorial from [[https://stackoverflow.com/questions/36467532/][this stackOverflow's Q&A]], I want to make it work in this App.


* [2018-6-18 Mon] MediaEditService as the data center for all elements of MediaEditComponent
I put all ~subject~s (the event emitter & listener) and datas into ~MediaEditService~ so that all the members of ~MediaEditComponent~ will use ~MediaEditService~ as the data center.
It works.

* [2018-6-12 Tue] Fail to run this App in Android device and emulator
Once I set the ~Debug mode = true~ on my Android Laptop, I can run this App on that device; however, nothing is shown up.
Besides, I cannot find ~adb~ in ~Android SDK~'s folder. Because of that, I cannot choose the one provided by Visual Studio which is running under Hyper-V whose performance is quite nice.

* [2018-6-11 Mon] Let angular can compile the stuffs for Windows
1. ~npm install --save-dev @types/winrt~ to let Angular can recognize ~Windows.Storage~ namespace.
2. Since ~documentsLibrary~ cannot be declared in ~appxmanifest~ file, I changed to use ~videosLibrary~ and it works.
3. Three roles: a.~video Element~, b.~File(Blob)~ and c.~StorageFile(Windows)~.
    b,c -> a: ~url=window.URL.createObjectURL(b)~. However, this method is not suitable for the ~File(plugin)~, it should be gotten from ~fileEntry.toURL()~.
    a -> b,c: ??? Fortunately, I don't need it at this moment.
    b -> c:   ~input=b.msDetachStrem();~, ~output= await c.openAsync();~ and copy ~b~ to ~c~ by ~Windows.Storage.RandomAccessStream.copyAndCloseAsync(input,output)~.
    c -> b:   ??? Hm. I still don't need it.

* [2018-6-8 Fri] Using cordova and its file plugin in Angular 6.
1. In ~tsconfig.json~ file, I added in ~"cordova-test/plugins"~ in its ~"typeRoots"~ so that angular can use the typescript's declarations inside.
2. In ~/src/tsconfig.app.json~ file, I added in
#+begin_src json
    "types": [
      "cordova",
      "cordova-plugin-file/types"
    ]
#+end_src
in its property ~compilerOptions~ so that I can use "cordova" and "cordova.file" in this code.
3. Oh, remember that, you need to run
#+begin_src sh
npm i --save-dev @types/cordova
#+end_src
to let angular can recognize the object ~cordova~.
However, if you want to check whether it is supported,
~!!cordova~ will throw an error. You'd better to use ~!!window.cordova~ to check whether it is supported.

By the way, because ~ng build~ will remove the target folder at first, it will cause ~cordova~ think that it is not a cordova project if the building is fail.
How to solve this problem?

WELL, ADD AN EMPTY ~www~ FOLDER INSIDE CAN MAKE IT WORK.

* [2018-6-7 Thu] Load local file and play it by File API.
At this moment, I still not use cordova's plugin. I still use ~File API~ to achieve my goal.
1. I can get ~FileList~ from ~input~ with type of ~file~.
2. Then I use ~window.URL.createObjectURL(file)~ to get a temporary URL.
3. If I feed it directly to ~[src]~ of the UIElement audio, it will say that it is unsafe; therefore, I create a new pipe to tell Angular 6 to accept this URL as mentioned in [[https://stackoverflow.com/questions/41319324/angular-2-http-request-audio-src-not-play][this stackOverflow's Q&A]].
4. Even I take out the ~type~ of the ~HtmlMediaElement~, it still can work. However, it cannot play the ~WMV~ movie.
    But, the ~WMV~ can be played in Windows UWP!!! Great! That's enough.

* [2018-6-6 Wed] Try to disable the zoom in/out behavior in windows UWP
Once I added in 
#+begin_src css
body{
    margin: 0;
    -ms-content-zooming: none;
}
#+end_src
the zooming behavior is disabled in Windows UWP.

* [2018-6-4 Mon] Try to use display:grid in css file.
Well, ~route-outlet~ itself is an empty one. If you want to control its size by grid, you need to contain it into a ~div~ and set the grid control on that container ~div~.

* [2018-6-4 Mon] A navbar has been added.
I'm reading [[https://css-tricks.com/snippets/css/a-guide-to-flexbox/][this article about flex]] to know how to settle a better layout.
I'll apply it in next commit with the route.

* [2018-6-2 Sat] How to use mat-icon?
Well, as mentioned in [[https://material.angular.io/guide/getting-started][this article]], I need to add 
#+begin_src html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
#+end_src
into ~index.html~ file.
This way is still work in Windows APP.

* [2018-6-1 Fri] Now, how to debug this code?
1. ~ng serve~ + ~DEBUG: Launch Chrome~ in VS Code.
    - By this way, you can set break point in VS Code and to see what's happened in this code.
    - The web page will be renewed once you save the file.
2. ~cd cordova-test && cordova build windows~ and then run it in VS2017.
    - Once I need to check how does it work and debug it in a windows App, I need to do so.

* [2018-5-31 Thu] Make it can be debugged in Visual Studio 2017
1. Add in ~<script src="cordova.js"></script>~ into ~index.html~ by the command shown below and you need to add an anchor in ~index.js~ as ~<!-- EntryOfCordovaJS -->~; otherwise, it still can work in VS2017 out of cordova's functions.

2. Use 
#+begin_src sh
ng build --output-path cordova/www/ --base-href /www/ && sed -i "s/.*EntryOfCordovaJS.*/  <script src='cordova.js'><\/script>" cordova-test/www/index.html
#+end_src
so that its output js files will be with their sourcemaps, which means that it can be debugged in VS 2017.
However, for ~prepareAngular6App.js~, I need to write it as
#+begin_src sh
"ng build --output-path cordova-test/www/ --base-href /www/   && sed -i \"s/.*EntryOfCordovaJS.*/  <script src='cordova.js'><\\/script> /\" cordova-test/www/index.html"
#+end_src
Note that, the ~"~ after ~sed~ cannot be ~'~; otherwise, it'll not work.

3. Use
#+begin_src 
    mklink /j cordova-test\platforms\windows\src src
#+end_src
to make a junction (just as soft link) to src so that it can be debugged in VS2017.

4. To avoid to do unnecessary Typescript compilation, you can add 
#+begin_src xml
    <PropertyGroup>
        <TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
    </PropertyGroup>
#+end_src
into your ~CordovaApp.Windows10.jsproj~ file to turn the compilation from VS2017 off since I'll compile it through angular 6.
* [2018-5-25 Fri] Yes, it can work for Windows 10 & Browser
The command for angular build should be
#+begin_src sh
ng build --prod --output-path cordova/www/ --base-href /www/
#+end_src
Now, I'm facing two problems.
1. how to debug it since it has been uglify?
2. how to use ~app~ which is ~WinJS.Application~ as the role of the class of ~App.xaml.cs~?

* [2018-5-23 Wed] ng is created with cordova
Following [[https://www.becompany.ch/en/blog/2016/10/19/creating-apache-cordova-app-with-angular2][this article]], we can make an angular with cordova.
#+begin_src sh
ng new cordova-ng-test
cd cordova-ng-test
cordova create cordova
#+end_src
